### ISSUE TITLE
Frequency and axis scale settings are broked ( for SSE/AVX2 )

### ISSUE THREAD

**Issue by qytek** [Auburns/FastNoiseSIMD#1]
When frequency and axis scales set to 1.0, the generated image is correct. 
When I set frequency to 0.01, the generated image is scaled on y axis, seems that scalemodifier or scale is only correct on x-axis.
In my case, CPU SIMD avx2 was detected. Tried to set to NO_SIMD_FALLBACK, then everything is correct.

**Comment by Auburn** [comment]
I just added this as a note in the currently brief documentation, the size of the z dimension must be above 8 (the size of AVX vectors). The solution for this for 2D images is to set the x size to 1 and move x to y and y to z, like so: 
m_Noise->GetNoiseSet( 0, 0, 0, 1, width, height);

This limitation is for performance reasons
