### ISSUE TITLE
F3 F4 and F5 distance for Cellular noise

### ISSUE THREAD

**Issue by thesteeltoenail** [Auburns/FastNoiseSIMD#10]
Would it be possible to add support for F3, F4, and F5 distances in Cellular noise?

**Comment by Auburn** [comment]
I will look into it

**Comment by thesteeltoenail** [comment]
Thanks!

**Comment by thesteeltoenail** [comment]
Maybe a system like this?
http://accidentalnoise.sourceforge.net/implicit.html#CellularGenerator
Also this may be of use
http://www.neilblevins.com/cg_education/cg_education.htm

**Comment by Auburn** [comment]
The system is used in ANL isn't very optimised and wouldn't support the different Distance2 functions that are there currently. I think I know a way to add it to the current system though.

**Comment by Auburn** [comment]
I added the feature in the latest commit/release. It works from 0 (closest), up to 3. This is as high as I could go without increasing the search radius on the cellular noise, which would have made it 4x slower.
