### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by robbmcleod** [Auburns/FastNoiseSIMD#12]
Hi Jordan, I made a Python wrapper for your library:

https://github.com/robbmcleod/PyFastNoiseSIMD

Would you be willing to add a link?

I wrapped the code in Python's `concurrent.futures` as well to allow for multi-threaded generation. It's pretty obvious that you intended the code to be implemented in threads due to the fill mechanics, so thanks for that, it made it very easy.

**Comment by Auburn** [comment]
Thanks for making this, it looks great.

Looking through the code quick, why do you have to run the cpu feature
check in python?

Is the C++ code compiled at runtime?

Also when compiling it looks like you are compiling all the different SIMD
levels together with all the flags set, not sure what happens then.

**Comment by robbmcleod** [comment]
The C++ code is compiled by the `setuptools.Extension()` object in the `setup.py` script.  However prior to compilation I run the `cpuinfo.py` script to generate the `#define` statements that are in [amd64_arch.h](https://github.com/robbmcleod/PyFastNoiseSIMD/blob/master/PyFastNoiseSIMD/FastNoiseSIMD/amd64_arch.h) (it's re-generated on build every time).  The alternative would be CMake but that's another dependency and more work.

You feel the SIMD levels should be XOR?  That's an easy enough fix.  I haven't tested the AVX2 support because I don't have a CPU that supports it.  I'll probably buy one next month.  

EDIT: do you know which bit-flags should be set on a CPU to indicate AVX512 and/or FMA support?  The `cpuinfo.py` script doesn't currently detector those optimizations.  At the same time, Python for Windows  is MSVC2015 at the latest (Linux would be a different story).

**Comment by Auburn** [comment]
The problem is you are compiling all of the source files with the same flags, you need to compile each FastNoiseSIMD_*.cpp with it's own corresponding flag.

Why don't you just compile all the SIMD levels and let FastNoise SIMD detect the support CPU features?

You should also use the /O3 flag for maximum optimisation.

**Comment by robbmcleod** [comment]
Ok, this will require some investigation into the `setuptools` module to see if building intermediate object files is supported by default or (more likely) if I have to subclass it.  I had a similar problem lately with the `blosc` compression library that had a namespace collision in `setuptools` that doesn't exist with the CMake build.
