### ISSUE TITLE
Changing the Collider of a chunk, while running the Game....[UNITY]

### ISSUE THREAD

**Issue by Fable67** [Auburns/FastNoiseSIMD#13]
Hello guys,
I bought the FastNoise Library inside the Asset Store of Unity, means I'm writing the Code in C#. Now I added the supported mesh Collider Generation to my Terrain. The Problem is, I want something like the Render Distance in the examples. So he's rendering like 10 Chunks in every x, y, z direction, but I want just like 5 Chunks Render Distance of The Colliders, so that a chunk being away like 7 chunks doesnt have the MeshCollider enabled to save processing Power. How can I do it??
Thanks.
Fable67

**Comment by Auburn** [comment]
Hi Fable,

You should add and additional check when chunk distances are checked for unloading, and if they within a certain distance generate collider meshes for them.
