### ISSUE TITLE
Adding and deleting blocks while run time in Unity/C#

### ISSUE THREAD

**Issue by Fable67** [Auburns/FastNoiseSIMD#14]
Hello Auburns,
Sorry that it's me asking again, but I'm just in love with your library and spend much time figuring out to add something to, cause I'm not so expirienced. So now my issue is that I wanna delete and add cubes, while I'm playing. I already programmed a script, that can get the single Cube I hitted with a RayCast. But I'm not abled to figure out how I can delete a cube (change the mesh) or add a cube (change the mesh). I'm using an expanded version of your tutorial, but the generation of terrain, chunks is the same. I would really appreciate some small example code, that was implemented inside the example.
Thanks for your help Auburns
Fable67

**Comment by Auburn** [comment]
Some thing like this in the chunk class:


```
public void SetVoxel(Voxel voxel, int localX, int localY, int localZ)
{
	TerrainGeneratorBase.ChunkFillUpdate(this, voxel);

	int voxelIndex = VoxelDataIndex(localX, localY, localZ);

	voxelData[voxelIndex] = voxel;

	dirtyMesh = true;
}
```
