### ISSUE TITLE
Readme/documentation suggestions

### ISSUE THREAD

**Issue by avaer** [Auburns/FastNoiseSIMD#16]
Seems like this lib does not support 2D noise, and the API is slightly different than `FastNoise`.

Ideally these would be implemented, but an easy win would be to just document this so the next person doesn't have to dig into the code to find out :).

**Comment by rokups** [comment]
If you set zSize to 1 then you basically get a 2d noise field.

Edit:
@modulesio this is how i generate 2d noise:

```cpp
float* noiseSet = noise_->GetSimplexFractalSet(y * (ySize - 1), x * (xSize - 1), 0, ySize, xSize, 1);
```

Input parameters:

* `x` - x offset of the grid
* `y` - y offset of the grid
* `xSize` - horizontal size of the grid
* `ySize` - vertical size of the grid

As you can see i have swapped `x` with `y` and `xSize` with `ySize`. Take a look at generated grids:

     2x2x1 set with offset 0;0
        0  0.1
      0.2 0.33
    
     2x2x1 set with offset 1;0
      0.2  0.33
      0.13 0.27

Notice how specifying x offset 1 shifts rows up. Swapping x and y "flips" set in a way that allows us indexing it using `set[y * xSize + x]` or simply `set[index++]`. Tiling works properly too.

P.S.
`x * (xSize - 1)`  makes later set generate edge values of previous set, you know so tiles join up. You might not need this depending on your application.

**Comment by perdugames** [comment]
I can not understand how to do it here:

`float* noiseSet = noise_->GetSimplexFractalSet(y * (ySize - 1), x * (xSize - 1), 0, ySize, xSize, 1);
`

if it's a float pointer I have, how do I get the values in a 2D array? because I'm creating a module, and I need to return a 2D array.

**Comment by Auburn** [comment]
It is a pointer to the array of values

**Comment by perdugames** [comment]
Yeah, I'm traveling, these last days I've got a bad head, it's that simple:

```
float a[2][2];
int index = 0;

for (int x = 0; x < 2; x++)
{
    for (int y = 0; y < 2; y++)
    {
       float a[x][y] = noiseSet[index++];
    }
}
```
or
` memcpy(a, noiseSet, sizeof(float)*4);
`
or
`std::copy(a, a + 4, noiseSet);
`

**Comment by perdugames** [comment]
I can not understand why `y * (ySize - 1), x * (xSize - 1)` even though you have read your PS. Could you give me more details of why do this?

**Comment by rokups** [comment]
In my case using `y * (ySize - 1), x * (xSize - 1)` as index flips patches so their edges fit together. In my case left-handed coordinates are used, positive X, Y & Z axes point to the right, up, and forward. terrain plane was x-z. My code snippet confusingly names z coordinate as y.

**Comment by PerduGames** [comment]
I do not have MSVC. I use voidlinux.

And what I'm working on. https://github.com/PerduGames/gdfastnoisesimd
