### ISSUE TITLE
artifacts on cellular distance with high Jitter

### ISSUE THREAD

**Issue by luckyrantanplan** [Auburns/FastNoiseSIMD#17]
Hello, 

There is problem of horizontal or vertical discontinuity that occurs more often when the Jitter >=0.8 for Cellular Distance ( Euclidian for example). It seems to me that the jitter move the feature points outside of there cube, so that the nearest neighbor distance algorithm on point inside cube cannot work. What do you think ? 

I would prefer that the jitter does not move the point outside of their cube.

cheers, 
Florian

**Comment by Auburn** [comment]
The default setting for cellular jitter (0.45) is high as it can go guaranteed artifact free, setting it higher than this will cause progressively more artifacts. Adding support for higher jitter would make the cellular noise function 5x slower, so it's not something I'm planning to add.
