### ISSUE TITLE
Doubt about the library and SIMD

### ISSUE THREAD

**Issue by perdugames** [Auburns/FastNoiseSIMD#19]
Sorry for the general question. I do not have much knowledge about what SIMD really is, although I researched it, I did not quite understand it. But I'm interested in using this library if that's what I'm thinking. Here it says it will run in parallel, thus being faster. But on any computer will it work after I compile my program?

Example:

I have my game that uses this library of noises to generate 2D terrain. After I compile the game and distribute it to the players, will I have any non-compatibility issues?

**Comment by Auburn** [comment]
The library will detect support on each CPU at runtime to ensure that only
code supported by that CPU is used, if needed there is a fallback to non
SIMD code, but all CPUs since 2003 should support some form of SIMD. This
library is already in use by a released PC title and there are no current
issues with compatibly.

**Comment by perdugames** [comment]
the fallback to SIMD code is automatic? what released PC title?

**Comment by Auburn** [comment]
Yes it is automatic. The game StarMade

**Comment by perdugames** [comment]
I played this game a year ago, I'm not following up. But if StarMade continues where it was going, it will be one of the best games of the genre.
And I was curious why it worked so well on my computer while others were running so badly. Must be why.

**Comment by perdugames** [comment]
I'm checking here, is not there 2D noise for the functions?

**Comment by Auburn** [comment]
There are currently no 2D SIMD noise functions but you can take a slice of
3D noise, this often gives a more interesting noise result as well. Have a
look at the other issue about 2D noise there is an example there

**Comment by perdugames** [comment]
but the 3D functions are not patented?

**Comment by Auburn** [comment]
See here: https://github.com/Auburns/FastNoise/issues/2

**Comment by perdugames** [comment]
I tried to compile here and get the error below, and I'm not sure where I get these files, are they part of what?

```
FastNoiseSIMD/ARM/cpu-features.c:72:10: fatal error: sys/system_properties.h: No such file or directory
 #include <sys/system_properties.h>
```

**Comment by Auburn** [comment]
Don't compile the /ARM/ folder unless you are compiling for ARM platform
(mobile), you can delete it.

**Comment by perdugames** [comment]
deletes, but now I get this error when trying to compile:

```
modules/gdfastnoisesimd/FastNoiseSIMD/FastNoiseSIMD/FastNoiseSIMD_avx2.cpp:37:2: error: #error To compile AVX2 add build command "-march=core-avx2" on FastNoiseSIMD_avx2.cpp, or remove "#define FN_COMPILE_AVX2" from FastNoiseSIMD.h
 #error To compile AVX2 add build command "-march=core-avx2" on FastNoiseSIMD_avx2.cpp, or remove "#define FN_COMPILE_AVX2" from FastNoiseSIMD.h
  ^~~~~
In file included from modules/gdfastnoisesimd/FastNoiseSIMD/FastNoiseSIMD/FastNoiseSIMD_avx2.cpp:48:0:
modules/gdfastnoisesimd/FastNoiseSIMD/FastNoiseSIMD/FastNoiseSIMD_internal.cpp: In function 'SIMDf L3_FUNC_Lerp(SIMDf, SIMDf, SIMDf)':
modules/gdfastnoisesimd/FastNoiseSIMD/FastNoiseSIMD/FastNoiseSIMD_internal.cpp:43:22: note: The ABI for passing parameters with 32-byte alignment has changed in GCC 4.6
 #define L_VAR2(x, l) L##l##_##x
                      ^
modules/gdfastnoisesimd/FastNoiseSIMD/FastNoiseSIMD/FastNoiseSIMD_internal.cpp:44:21: note: in expansion of macro 'L_VAR2'
 #define L_VAR(x, l) L_VAR2(x, l)
                     ^~~~~~
modules/gdfastnoisesimd/FastNoiseSIMD/FastNoiseSIMD/FastNoiseSIMD_internal.cpp:45:16: note: in expansion of macro 'L_VAR'
 #define VAR(x) L_VAR(x, SIMD_LEVEL)
                ^~~~~
modules/gdfastnoisesimd/FastNoiseSIMD/FastNoiseSIMD/FastNoiseSIMD_internal.cpp:46:17: note: in expansion of macro 'VAR'
 #define FUNC(x) VAR(FUNC_##x)
                 ^~~
modules/gdfastnoisesimd/FastNoiseSIMD/FastNoiseSIMD/FastNoiseSIMD_internal.cpp:679:25: note: in expansion of macro 'FUNC'
 static SIMDf VECTORCALL FUNC(Lerp)(SIMDf a, SIMDf b, SIMDf t)
```
edit:

I've been able to compile here by adding the flags: CXXFLAGS=['-std=c++11', '-march=core-avx2'], but will this make computers that require the avx2 instructions do not run?

**Comment by PerduGames** [comment]
I still can not get it to work, I'm now experiencing a flaw in segmentation when trying to start a new class in my module. I get this error while running my program: https://pastebin.com/V6tMFJ3F

I have this pointer:

`FastNoiseSIMD* myNoise;`

the builder of my class:

```
GDFastNoiseSIMD::GDFastNoiseSIMD(){

    myNoise = FastNoiseSIMD::NewFastNoiseSIMD();

}
```

and thus I call the methods:

`myNoise->GetSeed();`

Am I doing something wrong?
