### ISSUE TITLE
Build failure on aarch64/armv7l

### ISSUE THREAD

**Issue by QuLogic** [Auburns/FastNoiseSIMD#23]
The NEON file fails to build on [aarch64](https://kojipkgs.fedoraproject.org//work/tasks/7262/23967262/build.log) and [armv7l](https://kojipkgs.fedoraproject.org//work/tasks/7266/23967266/build.log) (Note these builds are for pyfastnoisesimd, but fail in code from here). The errors are like this:
```
pyfastnoisesimd/fastnoisesimd/FastNoiseSIMD_internal.cpp:201:50: note: use -flax-vector-conversions to permit conversions between vectors with differing element types or numbers of subparts
 #define SIMDf_BLENDV(a,b,mask) vbslq_f32(mask,b,a)
                                                  ^
pyfastnoisesimd/fastnoisesimd/FastNoiseSIMD_internal.cpp:778:12: note: in expansion of macro ‘SIMDf_BLENDV’
  SIMDf u = SIMDf_BLENDV(y, x, l8);
            ^~~~~~~~~~~~
pyfastnoisesimd/fastnoisesimd/FastNoiseSIMD_internal.cpp:201:50: error: cannot convert ‘MASK {aka __vector(4) int}’ to ‘uint32x4_t {aka __vector(4) unsigned int}’ for argument ‘1’ to ‘float32x4_t vbslq_f32(uint32x4_t, float32x4_t, float32x4_t)’
 #define SIMDf_BLENDV(a,b,mask) vbslq_f32(mask,b,a)
                                                  ^
```
and
```
pyfastnoisesimd/fastnoisesimd/FastNoiseSIMD_internal.cpp:115:47: error: ‘posix_memalign’ was not declared in this scope
 #define SIMD_ALLOCATE_SET(floatP, floatCount) posix_memalign((void**)&floatP, MEMORY_ALIGNMENT, (floatCount)* sizeof(float))
                                               ^
pyfastnoisesimd/fastnoisesimd/FastNoiseSIMD_internal.cpp:1055:2: note: in expansion of macro ‘SIMD_ALLOCATE_SET’
  SIMD_ALLOCATE_SET(noiseSet, size);
  ^~~~~~~~~~~~~~~~~
pyfastnoisesimd/fastnoisesimd/FastNoiseSIMD_internal.cpp:115:47: note: suggested alternative: ‘__builtin_posix_memalign’
 #define SIMD_ALLOCATE_SET(floatP, floatCount) posix_memalign((void**)&floatP, MEMORY_ALIGNMENT, (floatCount)* sizeof(float))
                                               ^
```

Should `-flax-vector-conversions` be added to the wiki for compiler settings or is something wrong with those files?

**Comment by QuLogic** [comment]
With #26 and `-flax-vector-conversions`, there are fewer errors, but both [`aarch64`](https://kojipkgs.fedoraproject.org//work/tasks/5865/24225865/build.log) and [`armv7hl`](https://kojipkgs.fedoraproject.org//work/tasks/5866/24225866/build.log) still fail due to a different type conversion:
```
pyfastnoisesimd/fastnoisesimd/FastNoiseSIMD_internal.cpp: In function ‘SIMDf L5_FUNC_SimplexSingle(SIMDi, SIMDf, SIMDf, SIMDf)’:
pyfastnoisesimd/fastnoisesimd/FastNoiseSIMD_internal.cpp:182:70: error: cannot convert ‘float32x4_t {aka __vector(4) float}’ to ‘MASK {aka __vector(4) int}’ in initialization
 #define SIMDf_GREATER_EQUAL(a,b) vreinterpretq_f32_u32(vcgeq_f32(a,b))
                                                                      ^
```

**Comment by Auburn** [comment]
I checked in a potential fix for the compile error, I can't test on arm64 right now so let me know if it works, thanks.

**Comment by QuLogic** [comment]
I think that change may be a bit backwards, based on my reading of the types in intrinsics. I am working on a patch that should get things working, I think.

**Comment by Auburn** [comment]
The intrinsic type casts on neon have their naming scheme flipped compared
to see/avx. I looked it up here:
https://gcc.gnu.org/onlinedocs/gcc-4.7.3/gcc/ARM-NEON-Intrinsics.html

**Comment by Auburn** [comment]
Ok, I looked over it a bit more. I think all the casts should be correct now, bear in mind that the casts have no runtime cost they are just for the compiler. Let me know how it goes

**Comment by Auburn** [comment]
Merged, let me know if I can close this. I think we should have another issue for the android cpu features replacement.
