### ISSUE TITLE
Different xSize and ySize issues in FillVectorSet

### ISSUE THREAD

**Issue by PZerua** [Auburns/FastNoiseSIMD#30]
I am getting repeated patterns when I set different sizes for x and y in ```FillVectorSet(FastNoiseVectorSet* vectorSet, int xSize, int ySize, int zSize);```. When I set the same size it looks at desired, is it mandatory?.

I am using ```FillNoiseSet(float* noiseSet, FastNoiseVectorSet* vectorSet, float xOffset = 0.0f, float yOffset = 0.0f, float zOffset = 0.0f);``` to get my noise since I want to apply an offset.

Here is an example code:

```
FastNoiseSIMD::FillVectorSet(&m_tVectorSet, 512, 256, 1);
m_ptFloatValues = FastNoiseSIMD::GetEmptySet(512, 256, 1);
m_ptNoise->FillNoiseSet(m_ptFloatValues, &m_tVectorSet, xOffset, yOffset, zOffset);
```

And an example image:

![noise](https://user-images.githubusercontent.com/8772233/38320082-e040025a-3833-11e8-94cf-e88b1e1b977b.png)

For ```xSize = 503``` and ```ySize = 200```:

![noise2](https://user-images.githubusercontent.com/8772233/38320252-5f0025d4-3834-11e8-93ec-abf4f20ebe1b.png)

Thanks.

**Comment by Auburn** [comment]
Looks like you are indexing the array of floats incorrectly, you can index it like this:
```
int index = 0;
for (int x = 0; x < 16; x++)
{
    for (int y = 0; y < 16; y++)
    {
        for (int z = 0; z < 16; z++)
        {
            ProcessVoxelData(x, y, z, noiseSet[index++]);			
        }			
    }
}
```

**Comment by PZerua** [comment]
It works, thanks! This is how I had my loops:

```
    // Update the texture
    for (unsigned y = 0; y < 256; ++y) {
        for (unsigned x = 0; x < 512; ++x) {

            // Get noise and map value to range 0 - 1 (add 1 and divide by 2)
            float value = (m_ptFloatValues[x + y * m_uiWidth] + 1) * 0.5f;

            // Convert to bgra uint and applying colors ...

            m_ptTextureData[x + y * 512] = bgra;
        }
    }
```
And now: 
```
    // Update the texture
    unsigned index = 0;
    for (unsigned x = 0; x < 512; ++x) {
        for (unsigned y = 0; y < 256; ++y) {

            // Get noise and map value to range 0 - 1 (add 1 and divide by 2)
            float value = (m_ptFloatValues[index++] + 1) * 0.5f;

            // Convert to bgra uint and applying colors ...

            m_ptTextureData[x + y * 512] = bgra;
        }
    }
```
