### ISSUE TITLE
Non understanding of compilation step

### ISSUE THREAD

**Issue by Hideman85** [Auburns/FastNoiseSIMD#35]
Hello,

I try to compile your lib using cmake I say your [Compilation Settings](https://github.com/Auburns/FastNoiseSIMD/wiki/Compiler-Settings)

Can you create a CMakeLists.txt for compilation pls?

Thanks in advance for your further response.

**Comment by Auburn** [comment]
https://github.com/Auburns/FastNoiseSIMD/pull/29
