### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Hideman85** [Auburns/FastNoiseSIMD#37]
Bellow I have some question about your library:

- How compile with MinGW which options use? I try MSVC options does not work.

- What use for cave generation? I try many different params with CellularNoise (with or not Perturb) but isn't look great.

Thanks in advance for your further responses.

**Comment by Auburn** [comment]
Try the GCC settings

![image](https://user-images.githubusercontent.com/1349548/48375886-34942200-e6c1-11e8-9d39-2cd2178c8610.png)

These are the noise settings used for the unity demo, where < 0.88 is solid

**Comment by NicolasRicard** [comment]
Hello,

Actually, there is too much ifdef _WIN32 in your sources, so it doesn't work.
Even if some may be justified, some of them should be ifdef MSVC

I tried with some changes until I can compile it with mingw, but I had a beautifull error 0x000005 :

Process finished with exit code -1073741819 (0xC0000005)

So I am a litle lost. It happened with this line :

```cpp
    float* results = noiseSIMD->GetPerlinSet(0, 0, 0, 200, 1, 200);
