### ISSUE TITLE
Any chance to see Library with double precision numbers?

### ISSUE THREAD

**Issue by Lucius256** [Auburns/FastNoiseSIMD#4]
Really need fast noise library for my planets game project. It was easy to change non-SIMD code from floats to doubles. But SIMd have problems. Will you add double precision support?

**Comment by Auburn** [comment]
Switching to doubles for SIMD would require some significant extra code if you want to avoid a 100% performance decrease due to halved vector size. I will look into it when I have some free time.

**Comment by ShuP1** [comment]
Is this planned for https://github.com/Auburn/FastNoise2 ?

**Comment by Auburn** [comment]
I've added it to the todo list, the design of FastNoise2 will make it easier to add but it will still be a lot of work. There are still a bunch of other features I want to add that are higher on the priority list though.
