### ISSUE TITLE
[Question] Use with UE4

### ISSUE THREAD

**Issue by Zbluu** [Auburns/FastNoiseSIMD#40]
First off, thanks for this amazing lib !

I'd like to know if someone has used this library into the Unreal Engine 4.
I do, and I have some mysterious compilation errors:
The lib can compile for small projects, but when I have more than 31 .cpp files, the compiler shows me incoherent errors (see the log [here](https://github.com/Auburns/FastNoiseSIMD/files/2993149/log.txt)).

To target the problem, I have created 2 projects, one with the library + 23 empty .cpp files, and another with the library + 24 empty .cpp files (I use empty .cpp files just to demonstrate the problem). The first project compiles normally, there are lots of warning, but I can use the lib normally. But the second can not compile at all. If you remove one of the empty .cpp files that I put into the project, it will compile (it's probably related to the Unity-Build feature, but i don't know anything about it).

This is my 2 projects, you can try yourself:
[ok_project.zip](https://github.com/Auburns/FastNoiseSIMD/files/2993170/ok_project.zip)
[fail_project.zip](https://github.com/Auburns/FastNoiseSIMD/files/2993171/fail_project.zip)
I tested them on two different computers, with different installations, with UE 4.21 and 4.19, and the problem is the same.

To compile with VS, I just needed to do some modifications on the FastNoiseSIMD_internal.cpp (because it wanted to have FastNoiseSIMD_internal.h as the first included header). 
So just for information, I have replaced this :
```cpp
#include "FastNoiseSIMD.h"
#include <assert.h> 

#if defined(SIMD_LEVEL) || defined(FN_COMPILE_NO_SIMD_FALLBACK)

#ifndef SIMD_LEVEL
#define SIMD_LEVEL FN_NO_SIMD_FALLBACK
#define SIMD_LEVEL_H FN_NO_SIMD_FALLBACK
#include "FastNoiseSIMD_internal.h"
#include <math.h>
#define FN_ALIGNED_SETS
#endif
```
By this :
```cpp
#if defined(SIMD_LEVEL) || defined(FN_COMPILE_NO_SIMD_FALLBACK)

#ifndef SIMD_LEVEL
#define SIMD_LEVEL FN_NO_SIMD_FALLBACK
#define SIMD_LEVEL_H FN_NO_SIMD_FALLBACK
#include "FastNoiseSIMD_internal.h"
#include "FastNoiseSIMD.h"
#include <math.h>
#define FN_ALIGNED_SETS
#endif
#include <assert.h>
```

And I also commented the `#define FN_COMPILE_AVX2` line, but this is just needed in my case I think.

Does anyone have any ideas to fix this ?

**Comment by Auburn** [comment]
Hi, you cannot include FastNoiseSIMD_internal.h in FastNoiseSIMD_internal.cpp it breaks how the multiple compile works for dynamic SIMD functionality. I suggest creating an empty dummy .h file to include as the first for all files. If you want AVX to work you will need to have it in a separate project and set bEnableAVX in the unreal project settings.

**Comment by Zbluu** [comment]
Oh, thanks for the AVX tip.
The problem is that the compiler needs the FastNoiseSIMD_internal.h to be the first header included, else it he won't want to compile :
```
Expected FastNoiseSIMD_internal.h to be first header included.	A:\Documents\TestNoise\Source\TestNoise\MyLib\FastNoiseSIMD_internal.cpp	1
```
So even with a dummy.h file, the problem is the same, or maybe I didn't understand you correctly. 

And thank you for taking the time to help me.

**Comment by Auburn** [comment]
If you set a dummy .h at the top of every file then it will expect that instead

**Comment by Auburn** [comment]
You probably also need to disable unity build, it might mess up the multiple compile of FastNoiseSIMD_internal.cpp

**Comment by Zbluu** [comment]
The dummy.h workaround is not an option :
```
Expected FastNoiseSIMD.h to be first header included A:\Documents\TestNoise\Source\TestNoise\MyLib\FastNoiseSIMD.cpp	1
Expected FastNoiseSIMD_internal.h to be first header included.	A:\Documents\TestNoise\Source\TestNoise\MyLib\FastNoiseSIMD_internal.cpp	1
```

I found another way, by comment this line 
`PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;`
in my build file, but I don't know the consequences of doing that.

And, with the Unity build disable, it seems ok and it compiles.
But with a large project such as unreal projects, disable the unity build is not an option for me. Is there another way ?

**Comment by Auburn** [comment]
Put FastNoise in it's own plugin, then you can set the settings you need
for it without messing with the rest of your project

**Comment by Zbluu** [comment]
I'll try that.
Thanks again for the help ☺️

EDIT : It works !

**Comment by JohnAlcatraz** [comment]
What I did is actually just compile it in it's very own VS project and use it as a static library with my UE4 project, that works best with UE4
