### ISSUE TITLE
Sampling at arbitrary positions

### ISSUE THREAD

**Issue by malytomas** [Auburns/FastNoiseSIMD#41]
Hi, the example in the wiki shows how to use the library in a 3D grid. I would like to provide my own 3D coordinates instead. Is that possible?
As an example imagine that I have an array of particles, and I want to deviate their movement based on the noise. Another example is to generate some properties for vertices of a general mesh.
Thanks

**Comment by Auburn** [comment]
Have a look at the VectorSet struct in the header, you can pass in an array of float vectors to any of the noise functions. It should be mostly self explanatory, let me know if you need some more guidance.

**Comment by malytomas** [comment]
Hi, thanks for quick reply. 
Just to be sure, does the following code show correct use of the vector set?
```c++
FastNoiseVectorSet fnvs(1000000);
for (int i = 0; i < 1000000; i++)
{
  fnvs.xSet[i] = foo[i][0];
  fnvs.ySet[i] = foo[i][1];
  fnvs.zSet[i] = foo[i][2];
}
float *es = FastNoiseSIMD::GetEmptySet(1000000);
FastNoiseSIMD *fns = FastNoiseSIMD::NewFastNoiseSIMD();
fns->FillValueSet(es, &fnvs);
for (int i = 0; i < 1000000; i++)
  bar[i] = es[i];
FastNoiseSIMD::FreeNoiseSet(es);
delete fns;
```

**Comment by Auburn** [comment]
That looks correct, does it work?

**Comment by malytomas** [comment]
I did not try it yet. I am already using your other library and I intend to wrap them both in common api and use the simd one where possible. I will let you know.
