### ISSUE TITLE
Scaling center is offset

### ISSUE THREAD

**Issue by TokisanGames** [Auburns/FastNoiseSIMD#42]
Hi, I'm exploring implementing FastNoiseSIMD in Godot. I've noticed that the center for the scaling factor on GetNoise is neither 0,0,0, nor the base position requested. This is causing me no end of trouble implementing terrains with LODs.

If I get a 2048x2048x1 2D slice of noise with a call like `GetNoise(0, 0, 0, 2048, 2048, 1, scale)`, then I would expect adjusting scale would mean the noise zooms in and out around 0,0,0, but it doesn't. GetNoise(0,0,0,2048,1,2048, scale) does the same thing. If I offset the beginning of the noise to (1557, 1005, 0), scaling happens around the center of the texture. If I begin at (1060, 670, 0) scaling happens around the top left point of the plane, which should be (0,0). These positions are just eyeball estimates using Cellular with a jitter of 0 (checkerboard).

I've used 2D to simplify my problems in 3D. Swapping Y & Z, it seems the Z offset is also 1005 for the center or 670 for (0,-,0), but I'm not completely sure about that. 

In my terrain, basically the Levels Of Detail are not lining up. Each higher LOD pulls noise at a scaling factor 2x the previous level. So my theory is that because the scale is offset to some strange point, and it may even be non-linear or non-static, given the above odd location, that when my LODs pull the noise data at higher scaling factors, they are offset from each other. Unfortunately, I haven't been able to manually line them up as I was able to do with 2D slices.

Is this a bug in FastNoiseSIMD?
Do you have a solution or workaround?
Do you know the true coordinates for the scaling center? And do they change based upon starting location of GetNoise, the data set size, the scaling factor, or other aspects?

Thanks

**Comment by Auburn** [comment]
Hi, I'm not sure why the scaling would be offset, the scale value provided to the function is used as a modifier for the frequency. There is no offset that I'm aware of, but it's been a while since I wrote the code, and it's not the easiest to look through. You could try using SetAxisScale instead see if that is any different. But the solution I would use would be to create a vector set for each LOD level and just pass in the offset you want the noise at.

Does the offset scaling happen with other noise types?

**Comment by TokisanGames** [comment]
Thanks for the response.

> You could try using SetAxisScale instead see if that is any different. 

SetAxisScale is offset by the same amount.

> Does the offset scaling happen with other noise types?

Yes

> But the solution I would use would be to create a vector set for each LOD level and just pass in the offset you want the noise at.

I'm already inserting a noise offset. I want to either know where the exact 3D noise offset currently is, or to eliminate the built in offset for the scaling center.

I've made a video demonstrating the issue.
https://youtu.be/7sGrzOMvOcM

I see the GetVectorSet code and this [discussion](https://github.com/Auburns/FastNoiseSIMD/issues/41#issuecomment-531611864) 
>you can pass in an array of float vectors to any of the noise functions

I don't understand what it's used for. You saw in my video I'm already specifying the beginning coordinates for the noise and using an offset to align the scaling center. 

As for the LODs in my 3D terrain, which is my only concern, I'm using:
```
GetNoiseSet(origin.x, origin.y, origin.z, size.x, size.y, size.z, 1<<lod);
```
where origin is a Vector3 of the origin point of the current landscape chunk in global coordinates. Size is 16,16,16, and the level of detail is used as a scaling factor. LOD0 is highest detail and a scale of 1. LOD1 is a scale of 2, LOD2 is 4.

The issue is the LODS don't line up with each other, likely due to the scaling center being in some random place, which means the different LOD chunks are not levels of detail of the same noise pattern, but of different ones.

Now that you've seen my video, do you still think GetVectorSet is the solution?

Thanks

**Comment by Auburn** [comment]
Hi, just tested this myself using a modified FastNoiseSIMD Preview. All the noise types scale around 0,0,0 as expected using the scale parameter in GetNoiseSet, so I don't think it's an issue with the function.

Shouldn't your origin be adjusted for your lod scale? Since the scale value just modifies the frequency

`GetNoiseSet(origin.x>>lod, origin.y>>lod, origin.z>>lod, size.x, size.y, size.z, 1<<lod);`

**Comment by TokisanGames** [comment]
> Shouldn't your origin be adjusted for your lod scale? Since the scale value just modifies the frequency
> 
> `GetNoiseSet(origin.x>>lod, origin.y>>lod, origin.z>>lod, size.x, size.y, size.z, 1<<lod);`

You're a genius! It's perfect. Thank you!
