### ISSUE TITLE
Accessing in Node.JS

### ISSUE THREAD

**Issue by alexwaeseperlman** [Auburns/FastNoiseSIMD#6]
I want to write programs that use this in node.js. I know that node.js is capable of doing this I just don't know how.
Do you plan on adding support in the future?

**Comment by Auburn** [comment]
http://stackoverflow.com/questions/9629677/how-can-i-use-a-c-library-from-node-js

**Comment by alexwaeseperlman** [comment]
I'm having errors compiling it into a .so file on my windows machine.

**Comment by Auburn** [comment]
.so is for Linux, use .dll for Windows
