### ISSUE TITLE
Generating 2d noise.

### ISSUE THREAD

**Issue by alexwaeseperlman** [Auburns/FastNoiseSIMD#7]
The documentation only shows how to generate 3d Simplex Fractals. How do the other noise types work in 2d?

**Comment by Auburn** [comment]
FastNoiseSIMD doesn't have an 2D noise, it's all 3D.

**Comment by alexwaeseperlman** [comment]
Is there an efficient way of getting a slice? Or should I just do a 3d with 8 depth and get a slice.

**Comment by Auburn** [comment]
You can just swap axis and make x or y a size 1

**Comment by alexwaeseperlman** [comment]
Will that make it slow? It says in the documentation that it should be a multiple of 8 for optimal speed.

**Comment by Auburn** [comment]
Only the Z axis needs to be a multiple of 8

**Comment by alexwaeseperlman** [comment]
Okay thank you!

**Comment by sfla** [comment]
If I want a 2D noise, would it be better to use FastNoiseSIMD and get a slice, or use "FastNoise" (the non-SIMD-version) instead?

**Comment by Auburn** [comment]
https://github.com/Auburns/FastNoise#performance-comparisons

SIMD would be faster in most cases, you also get better quality noise by taking a slice of 3D
