### ISSUE TITLE
Any plans on adding 4D support?

### ISSUE THREAD

**Issue by plattfot** [Auburns/FastNoiseSIMD#9]
I'm looking to replace a proprietary noise library (Houdini's UT_Noise), with something faster. But I need 4D noise. Any plans on expanding your FastNoiseSIMD to support 4D?

**Comment by Auburn** [comment]
Adding 4D for all noise types would be a large undertaking, there are currently no plans for adding it.

**Comment by plattfot** [comment]
Understandable, thanks anyway.
